[workspace]
members = [
    "kernel",
    # "boot",      # we'll add when we make a bootloader crate
    # "drivers",   # add later
    # "lib",       # add later
    # "user",      # userland apps
    # "fs"         # filesystem implementations
]

resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

lto = true
opt-level = 3
